# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'MockApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'RealmSwift'
    pod 'R.swift'
 	pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'Kingfisher'
    pod 'FSPagerView'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
   

  # Pods for MockApp

  target 'MockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MockAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
